"""mailings table

Revision ID: 3d726f7913b5
Revises: df79f523c939
Create Date: 2026-08-18 15:15:52.724622

"""
from alembic import op
import sqlalchemy as sa


revision = '3d726f7913b5'
down_revision = 'df79f523c939'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('button_text', sa.String(length=64), nullable=True),
    sa.Column('button_url', sa.String(length=512), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['seller_bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailings_seller_id'), 'mailings', ['seller_id'], unique=False)
    op.create_index(op.f('ix_mailings_status'), 'mailings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mailings_status'), table_name='mailings')
    op.drop_index(op.f('ix_mailings_seller_id'), table_name='mailings')
    op.drop_table('mailings')
    # ### end Alembic commands ###
