"""payout last error

Revision ID: 6158daf99d33
Revises: 9ce68e6baa2c
Create Date: 2026-08-21 08:28:03.731812

"""
from alembic import op
import sqlalchemy as sa


revision = '6158daf99d33'
down_revision = '9ce68e6baa2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payouts', sa.Column('last_error', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payouts', 'last_error')
    # ### end Alembic commands ###
