"""shop events for stats

Revision ID: 9ce68e6baa2c
Revises: a1b2c3d4e5f6
Create Date: 2026-08-19 14:21:38.480569

"""
from alembic import op
import sqlalchemy as sa


revision = '9ce68e6baa2c'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['seller_bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_events_bot_id'), 'shop_events', ['bot_id'], unique=False)
    op.create_index('ix_shop_events_bot_type', 'shop_events', ['bot_id', 'type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shop_events_bot_type', table_name='shop_events')
    op.drop_index(op.f('ix_shop_events_bot_id'), table_name='shop_events')
    op.drop_table('shop_events')
    # ### end Alembic commands ###
