"""channels table

Revision ID: df79f523c939
Revises: 0e7490ba439d
Create Date: 2026-08-18 15:00:27.139293

"""
from alembic import op
import sqlalchemy as sa


revision = 'df79f523c939'
down_revision = '0e7490ba439d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('auto_accept', sa.Boolean(), nullable=False),
    sa.Column('greeting_text', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['seller_bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_index(op.f('ix_channels_bot_id'), 'channels', ['bot_id'], unique=False)
    op.create_index(op.f('ix_channels_seller_id'), 'channels', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channels_seller_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_bot_id'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
